name: 'JavaScript Action Template'

description: 'Add description here'

inputs:
  input-1:
    description: 'Add a description here'
    required: true

outputs:
  output-1:
    description: 'Add a description here'

runs:
  using: 'node20'
  main: 'dist/index.js'
